language: generic
sudo: required
env:
  global:
    - PATH=${TRAVIS_BUILD_DIR/bats/bin}:${PATH}
addons:
  apt:
    packages:
      - bash
services:
  - docker

install:
  - "./build_workers.sh"

script:
  - "test.sh"
